// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UTOP.Booking.Infrastructure.Persistence;

#nullable disable

namespace UTOP.Booking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260721083053_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UTOP.Booking.Domain.Aggregates.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmendmentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("amendment_version");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("booking_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("group_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operator_id");

                    b.Property<string>("PilgrimageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pilgrimage_id");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("route");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("row_version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Passengers", "UTOP.Booking.Domain.Aggregates.Booking.Passengers#PassengerCount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Adults")
                                .HasColumnType("integer")
                                .HasColumnName("adults");

                            b1.Property<int>("Children")
                                .HasColumnType("integer")
                                .HasColumnName("children");

                            b1.Property<int>("Infants")
                                .HasColumnType("integer")
                                .HasColumnName("infants");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("uq_bookings_booking_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_bookings_group_id")
                        .HasFilter("group_id IS NOT NULL");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("ix_bookings_operator");

                    b.HasIndex("PilgrimageId")
                        .HasDatabaseName("ix_bookings_pilgrimage_id")
                        .HasFilter("pilgrimage_id IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_bookings_status");

                    b.ToTable("bookings", "utop_booking");
                });

            modelBuilder.Entity("UTOP.Booking.Domain.Entities.Itinerary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("arrival_city");

                    b.Property<string>("ArrivalCountry")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("arrival_country");

                    b.Property<string>("ArrivalPoint")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("arrival_airport");

                    b.Property<DateTimeOffset>("ArrivalUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_utc");

                    b.Property<string>("CarrierReference")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("carrier_reference");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departure_city");

                    b.Property<string>("DepartureCountry")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("departure_country");

                    b.Property<string>("DeparturePoint")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("departure_airport");

                    b.Property<DateTimeOffset>("DepartureUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_utc");

                    b.Property<string>("ServiceClass")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("service_class");

                    b.Property<Guid>("booking_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartureUtc")
                        .HasDatabaseName("ix_itineraries_departure");

                    b.HasIndex("booking_id")
                        .IsUnique();

                    b.ToTable("itineraries", "utop_booking");
                });

            modelBuilder.Entity("UTOP.Booking.Domain.Entities.Passenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("nationality");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("passenger_type");

                    b.Property<Guid>("booking_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("booking_id");

                    b.ToTable("passengers", "utop_booking");
                });

            modelBuilder.Entity("UTOP.Booking.Infrastructure.Persistence.IdempotencyKeyEntity", b =>
                {
                    b.Property<string>("KeyHash")
                        .HasColumnType("character(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("KeyHash");

                    b.ToTable("idempotency_keys", "utop_booking");
                });

            modelBuilder.Entity("UTOP.Booking.Infrastructure.Persistence.OutboxEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox_events", "utop_booking");
                });

            modelBuilder.Entity("UTOP.Booking.Domain.Aggregates.Booking", b =>
                {
                    b.OwnsOne("UTOP.Shared.Domain.ValueObjects.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("NUMERIC(18,4)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("currency");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings", "utop_booking");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("TotalPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("UTOP.Booking.Domain.Entities.Itinerary", b =>
                {
                    b.HasOne("UTOP.Booking.Domain.Aggregates.Booking", null)
                        .WithOne("Itinerary")
                        .HasForeignKey("UTOP.Booking.Domain.Entities.Itinerary", "booking_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UTOP.Booking.Domain.Entities.Passenger", b =>
                {
                    b.HasOne("UTOP.Booking.Domain.Aggregates.Booking", null)
                        .WithMany("PassengerList")
                        .HasForeignKey("booking_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UTOP.Booking.Domain.Aggregates.Booking", b =>
                {
                    b.Navigation("Itinerary")
                        .IsRequired();

                    b.Navigation("PassengerList");
                });
#pragma warning restore 612, 618
        }
    }
}
